# Поддержка проекта NormalDance

# GitHub Sponsors
github: [AENDYSTUDIO]

# Другие платформы
patreon: normaldance
open_collective: normaldance
ko_fi: normaldance
tidelift: "npm/normaldance"
community_bridge: normaldance
liberapay: normaldance
issuehunt: AENDYSTUDIO
otechie: AENDYSTUDIO

# Кастомные ссылки
custom: ["https://normaldance.com/donate", "https://normaldance.com/sponsor"]