{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "normaldance.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "normaldance.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.additionalLabels }}
    {{- toYaml .Values.serviceAccount.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}